; platformio.ini
[env:esp32dev-rx]
platform = espressif32@6.9.0
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = +<rx_main.cpp>

[env:esp32dev-tx]
platform = espressif32@6.9.0
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = +<tx_main.cpp>
lib_deps = 
    adafruit/Adafruit MPU6050
    adafruit/Adafruit Unified Sensor
    Wire

[env:get_mac_classic]
platform = espressif32@6.9.0
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = +<get_mac.cpp>

[env:get_mac_s3]
platform = espressif32@6.9.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_src_filter = +<get_mac.cpp>

[env:test_motor]
platform = espressif32@6.9.0
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = +<test_motor.cpp>