[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

[env:transmissor]
build_src_filter = +<transmissor/>

[env:receptor]
build_src_filter = +<receptor/>

[env:mac]
build_src_filter = +<mac/>